version: "3"

services:
  development:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=UTC
    volumes:
      - ..:/workspaces/development:cached
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
